### ISSUE TITLE
Agile Development /All About Trees /week 1

### ISSUE THREAD

**Issue by SarahNaji12** [HYF-Class20/agile-development-group5-all-about-trees#2]
- [x] [repo](https://github.com/_/_) (with a complete README)
- [x] [live demo](https://_.github.io/_)
- [/planning](https://github.com/_/_/tree/master/planning)
  - [x] constraints
  - [x] communication plan
  - [x] user personas
  - [ ] backlog
  - [ ] design
  - [ ] development strategy
  - [ ] retrospective
- [ ] [project board](https://github.com/_/_/projects/1)

**Comment by Biniam2023** [comment]
I assigned to all group members and I updated the link. Thank you reminding.

> Deliverable issue must be in [home class repo](https://github.com/HYF-Class20/home/issues) and in [Deliverables Project Board](https://github.com/orgs/HYF-Class20/projects/1) @Biniam2023 already created [agile-development-group5-all-about-trees](https://github.com/HYF-Class20/home/issues/70) but he didn't assign the group members and didn't update the links yet.
